### ISSUE TITLE
few improvements

### ISSUE THREAD

**Issue by rybbchao** [weizard/fops#1]
Hi, this is Duncan from Trend Micro.

Thanks for spending time for the test and there are few improvement suggestions:

- [x] 1. Try organizing your repository structure. (For example, [golang-standards/project-layout](https://github.com/golang-standards/project-layout))
- [x] 2. Try using build time flags to set application version instead of setting hard-coded value at runtime.
- [x] 3. It is great you integrated the build process and published the artifact to GitHub release. But DO NOT commit the artifact into the git repository. 

Feel free to let me know if you have any questions.

**Comment by weizard** [comment]
1. I knew "golang-standards/project-layout" this project, but I don't know when should I use this layout or don't use this. Because I saw some simple command line project won't use this layout. But I'm not sure it's they are too old or they didn't need. So your suggestion is that all  new project should follow this layout?

2. Thanks for this suggestion I heard this first time

**Comment by rybbchao** [comment]
Thanks for the commits. For 1, the directory `pkg/` is the root of package, so you should put the code in the sub-directory eg. `pkg/file` and the package name is `file`. It is ok for small projects to have no structure. But a project with good structure makes it easier to understand and maintain.

**Comment by weizard** [comment]
update project structure again, please review and give some feedback thanks

**Comment by rybbchao** [comment]
Reviewed, thanks for the work.
Also, nice to see you use `git tag` as the application version. Close now.
